### ISSUE TITLE
pytest and idapython

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/ida-netnode#7]
```
saved filedescriptor not valid anymore
```

**Comment by williballenthin** [comment]
this is an issue with pytest capturing output. fix described here: http://stackoverflow.com/a/26831328/87207

```
pytest.main("--capture=sys")
```

**Comment by nirizr** [comment]
I'm curious, are you running pytest tests within IDA?
How do you usually test this code? By manually running it within an IDA instance?

**Comment by williballenthin** [comment]
yes, running pytest tests within IDA. you need to kick off the test as a standalone script.

i suppose you could invoke IDA in bulk/scripting mode, but since i'm really only deving on my local workstation, its probably overkill. wish i could integrate with a CI service, but obviously can't distribute the IDA install.

**Comment by nirizr** [comment]
I'm not sure if this will interest you, but I'm planning to take another approach for IDAPython testing - I'm going to mock IDAPython. At least the parts of IDAPython I need, and will probably find a way to use code from the idapython repo instead of duplicating it myself.
I only just began, but you can find the repository here: https://github.com/nirizr/pytest-idapro

**Comment by williballenthin** [comment]
neat! i'll keep my eye on that project.
